"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function formatRupees(amount: number) {
  return `Rs. ${amount.toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

export default function AdminReportsPage() {
  const exportOrdersPDF = async () => {
    try {
      const response = await fetch("/api/reports/orders");

      if (!response.ok) {
        alert("Failed to generate report.");
        return;
      }

      const orders = await response.json();

      const doc = new jsPDF();

      const totalRevenue = orders.reduce(
        (sum: number, order: any) => sum + Number(order.total || 0),
        0
      );

      const pendingPayments = orders.filter(
        (o: any) => o.payment_status === "pending"
      ).length;

      const deliveredOrders = orders.filter(
        (o: any) => o.fulfillment_status === "delivered"
      ).length;

      // --------------------
      // HEADER
      // --------------------

      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.text("CARTIQ", 105, 18, { align: "center" });

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.text("Smart AI E-Commerce Platform", 105, 25, {
        align: "center",
      });

      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("ORDERS REPORT", 105, 38, {
        align: "center",
      });

      doc.setDrawColor(180);
      doc.line(14, 45, 196, 45);

      // --------------------
      // REPORT DETAILS
      // --------------------

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");

      doc.text(
        `Generated On : ${new Date().toLocaleDateString()}`,
        14,
        55
      );

      doc.text("Generated By : Admin", 14, 62);

      // --------------------
      // SUMMARY
      // --------------------

      doc.setFont("helvetica", "bold");
      doc.text("Summary", 14, 75);

doc.setFont("courier", "normal");
      doc.text(`Total Orders : ${orders.length}`, 20, 84);

      doc.text(
        `Total Revenue : ${formatRupees(totalRevenue)}`,
        20,
        91
      );

      doc.text(
        `Pending Payments : ${pendingPayments}`,
        20,
        98
      );

      doc.text(
        `Delivered Orders : ${deliveredOrders}`,
        20,
        105
      );

      // --------------------
      // TABLE
      // --------------------

      autoTable(doc, {
        startY: 115,

        head: [[
          "Order",
          "Customer",
          "Total",
          "Payment",
          "Fulfillment",
          "Date",
        ]],

        body: orders.map((order: any) => [
          order.order_number,
          order.email,
          formatRupees(Number(order.total || 0)),
          order.payment_status,
          order.fulfillment_status,
          new Date(order.created_at).toLocaleDateString(),
        ]),

        headStyles: {
          fillColor: [34, 34, 34],
        },

styles: {
  font: "courier",
  fontSize: 9,
  cellPadding: 3,
},
      });

      // --------------------
      // FOOTER
      // --------------------

      const pageHeight = doc.internal.pageSize.height;

      doc.setDrawColor(180);

      doc.line(14, pageHeight - 18, 196, pageHeight - 18);

      doc.setFontSize(10);

      doc.text(
        "Generated automatically by CartIQ",
        14,
        pageHeight - 10
      );

      doc.text(
        `Page 1`,
        196,
        pageHeight - 10,
        {
          align: "right",
        }
      );

      doc.save("CartIQ-Orders-Report.pdf");
    } catch (err) {
      console.error(err);
      alert("Check browser console.");
    }
  };

  const reports = [
    {
      title: "Sales Report",
      description: "Export complete sales data as a PDF.",
      button: "Export PDF",
      action: undefined,
    },
    {
      title: "Orders Report",
      description: "Download all customer orders as a PDF.",
      button: "Export PDF",
      action: exportOrdersPDF,
    },
    {
      title: "Inventory Report",
      description: "Generate a report of all products and stock levels.",
      button: "Export PDF",
      action: undefined,
    },
    {
      title: "Customer Report",
      description: "Export customer details and purchase history.",
      button: "Export PDF",
      action: undefined,
    },
    {
      title: "Sales Excel",
      description: "Download sales data in Excel format.",
      button: "Export Excel",
      action: undefined,
    },
  ];

  return (
    <div className="space-y-6">
      <div>
        <p className="text-sm uppercase tracking-[0.2em] text-zinc-500">
          Reports
        </p>

        <h1 className="mt-2 text-3xl font-semibold text-zinc-950">
          Reports & Exports
        </h1>

        <p className="mt-2 text-zinc-600">
          Generate and download business reports.
        </p>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        {reports.map((report) => (
          <div
            key={report.title}
            className="rounded-[28px] border border-black/5 bg-white p-6 shadow-sm"
          >
            <h2 className="text-xl font-semibold">{report.title}</h2>

            <p className="mt-2 text-sm text-zinc-600">
              {report.description}
            </p>

            <button
              onClick={report.action}
              disabled={!report.action}
              className={`mt-6 rounded-xl px-5 py-3 text-white transition ${
                report.action
                  ? "bg-zinc-900 hover:bg-zinc-800"
                  : "bg-zinc-400 cursor-not-allowed"
              }`}
            >
              {report.button}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}